In [2]:
import requests

In [21]:
years = list(range(1991, 2022))

In [3]:
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

In [3]:
for year in years:
    url = url_start.format(year)
    data = requests.get(url)
    
    with open("mvp/{}.html".format(year), "w+", encoding = "utf-8") as f:
              f.write(data.text)

## Get specific year

In [8]:
url = url_start.format(2021)
data = requests.get(url)

with open("mvp/{}.html".format(2021), "w+", encoding = "utf-8") as f:
    f.write(data.text)

In [9]:
from bs4 import BeautifulSoup

In [10]:
with open("mvp/1991.html", encoding = "utf-8") as f:
    page = f.read()

In [11]:
soup = BeautifulSoup(page, "html.parser")

In [12]:
soup.find('tr', class_='over_header').decompose()

In [13]:
mvp_table = soup.find_all(id = "mvp")

In [14]:
import pandas as pd

In [15]:
mvp_1991 = pd.read_html(str(mvp_table))[0]

In [20]:
pd.read_html(str(soup.find_all(id = "mvp")))

[   Rank             Player  Age   Tm  First  Pts Won  Pts Max  Share   G  \
 0     1     Michael Jordan   27  CHI   77.0    891.0      960  0.928  82
 1     2      Magic Johnson   31  LAL   10.0    497.0      960  0.518  79
 2     3     David Robinson   25  SAS    6.0    476.0      960  0.496  82
 3     4    Charles Barkley   27  PHI    2.0    222.0      960  0.231  67
 4     5        Karl Malone   27  UTA    0.0    142.0      960  0.148  82
 5     6      Clyde Drexler   28  POR    1.0     75.0      960  0.078  82
 6     7      Kevin Johnson   24  PHO    0.0     32.0      960  0.033  77
 7     8  Dominique Wilkins   31  ATL    0.0     29.0      960  0.030  81
 8    9T         Larry Bird   34  BOS    0.0     25.0      960  0.026  60
 9    9T       Terry Porter   27  POR    0.0     25.0      960  0.026  81
 10   11      Patrick Ewing   28  NYK    0.0     20.0      960  0.021  81
 11   12      John Stockton   28  UTA    0.0     15.0      960  0.016  82
 12   13       Isiah Thomas   29  DET    0.0     11.0      960  0.011  48
 13   14      Robert Parish   37  BOS    0.0     10.0      960  0.010  81
 14   15         Joe Dumars   27  DET    0.0      8.0      960  0.008  80
 15   16       Bernard King   34  WSB    0.0      7.0      960  0.007  64
 16   17        Kenny Smith   25  HOU    0.0      5.0      960  0.005  78
 17   18    Hakeem Olajuwon   28  HOU    0.0      4.0      960  0.004  56
 18  19T       Tim Hardaway   24  GSW    0.0      1.0      960  0.001  82
 19  19T       Kevin McHale   33  BOS    0.0      1.0      960  0.001  68

       MP   PTS   TRB   AST  STL  BLK    FG%    3P%    FT%    WS  WS/48
 0   37.0  31.5   6.0   5.5  2.7  1.0  0.539  0.312  0.851  20.3  0.321
 1   37.1  19.4   7.0  12.5  1.3  0.2  0.477  0.320  0.906  15.4  0.251
 2   37.7  25.6  13.0   2.5  1.5  3.9  0.552  0.143  0.762  17.0  0.264
 3   37.3  27.6  10.1   4.2  1.6  0.5  0.570  0.284  0.722  13.4  0.258
 4   40.3  29.0  11.8   3.3  1.1  1.0  0.527  0.286  0.770  15.5  0.225
 5   34.8  21.5   6.7   6.0  1.8  0.7  0.482  0.319  0.794  12.4  0.209
 6   36.0  22.2   3.5  10.1  2.1  0.1  0.516  0.205  0.843  12.7  0.220
 7   38.0  25.9   9.0   3.3  1.5  0.8  0.470  0.341  0.829  11.4  0.177
 8   38.0  19.4   8.5   7.2  1.8  1.0  0.454  0.389  0.891   6.6  0.140
 9   32.9  17.0   3.5   8.0  2.0  0.1  0.515  0.415  0.823  13.0  0.235
 10  38.3  26.6  11.2   3.0  1.0  3.2  0.514  0.000  0.745  10.0  0.155
 11  37.8  17.2   2.9  14.2  2.9  0.2  0.507  0.345  0.836  14.0  0.217
 12  34.5  16.2   3.3   9.3  1.6  0.2  0.435  0.292  0.782   3.4  0.098
 13  30.1  14.9  10.6   0.8  0.8  1.3  0.598  0.000  0.767  10.0  0.198
 14  38.1  20.4   2.3   5.5  1.1  0.1  0.481  0.311  0.890   9.9  0.155
 15  37.5  28.4   5.0   4.6  0.9  0.3  0.472  0.216  0.790   3.5  0.070
 16  34.6  17.7   2.1   7.1  1.4  0.1  0.520  0.363  0.844   9.0  0.161
 17  36.8  21.2  13.8   2.3  2.2  3.9  0.508  0.000  0.769   8.6  0.201
 18  39.2  22.9   4.0   9.7  2.6  0.1  0.476  0.385  0.803   9.9  0.148
 19  30.4  18.4   7.1   1.9  0.4  2.1  0.553  0.405  0.829   7.9  0.182  ]

In [67]:
years = list(range(1991, 2023))
dfs = []
for year in years:
    with open("mvp/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()
    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_='over_header').decompose()
    mvp_table = soup.find_all(id = "mvp")
    mvp = pd.read_html(str(mvp_table))[0]
    mvp["Year"] = year
    
    dfs.append(mvp)

In [68]:
mvps = pd.concat(dfs)

In [69]:
mvps

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,8,Stephen Curry,33,GSW,0.0,4.0,1000,0.004,64,34.5,...,5.2,6.3,1.3,0.4,0.437,0.380,0.923,8.0,0.173,2022
8,9,Chris Paul,36,PHO,0.0,2.0,1000,0.002,65,32.9,...,4.4,10.8,1.9,0.3,0.493,0.317,0.837,9.4,0.210,2022
9,10T,DeMar DeRozan,32,CHI,0.0,1.0,1000,0.001,76,36.1,...,5.2,4.9,0.9,0.3,0.504,0.352,0.877,8.8,0.154,2022
10,10T,Kevin Durant,33,BRK,0.0,1.0,1000,0.001,55,37.2,...,7.4,6.4,0.9,0.9,0.518,0.383,0.910,8.4,0.198,2022
11,10T,LeBron James,37,LAL,0.0,1.0,1000,0.001,56,37.2,...,8.2,6.2,1.3,1.1,0.524,0.359,0.756,7.5,0.172,2022

In [70]:
mvps.to_csv("mvps.csv")

In [81]:
from selenium import webdriver

In [82]:
driver = webdriver.Chrome(executable_path = "C:/Users/aniqp/Documents/chromedriver_win32/chromedriver.exe")

<ipython-input-82-68bc56285d7d>:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(executable_path = "C:/Users/aniqp/Documents/chromedriver_win32/chromedriver.exe")

In [ ]:
import time

player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

year = 1991
url = player_stats_url.format(1991)

driver.get(url)
driver.execute_script("window.scrollTo(1,10000)")
time.sleep(2)

html=driver.page_source

In [ ]:
with open("player/{}.html".format(year), "w+", encoding = "utf-8") as f:
    f.write(html)

In [62]:
years = list(range(1991, 2024))
for year in years:
    url = player_stats_url.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html=driver.page_source    
    with open("player/{}.html".format(year), "w+", encoding = "utf-8") as f:
        f.write(html)

In [63]:
dfs = []
for year in years:
    with open("player/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_='thead').decompose()
    player_table = soup.find_all(id = "per_game_stats")
    player = pd.read_html(str(player_table))[0]
    player["Year"] = year
    dfs.append(player)

In [64]:
players = pd.concat(dfs)

In [65]:
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,484,Delon Wright,PG,30,WAS,4,0,22.8,2.5,6.0,...,1.0,1.5,2.5,3.3,2.8,1.0,1.0,1.3,6.5,2023
509,485,McKinley Wright IV,PG,24,DAL,2,0,4.0,0.5,2.0,...,1.0,0.5,1.5,1.5,0.5,0.0,0.0,0.0,1.0,2023
510,486,Thaddeus Young,PF,34,TOR,26,9,17.2,2.2,4.2,...,1.7,2.0,3.8,1.9,1.0,0.1,0.7,1.7,5.1,2023
511,487,Trae Young,PG,24,ATL,27,27,35.7,8.7,21.2,...,0.7,2.0,2.7,9.9,0.7,0.1,3.8,1.5,27.0,2023
512,488,Ivica Zubac,C,25,LAC,30,30,29.5,4.0,6.4,...,3.3,7.5,10.8,1.1,0.4,1.6,2.1,3.1,10.1,2023

In [71]:
players.to_csv("players.csv")

In [73]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

In [85]:
import requests

for year in years:
    url = team_stats_url.format(year)
    data = requests.get(url)

    with open("team/{}.html".format(year), "w+", encoding = "utf-8") as f:
        f.write(data.text)

In [86]:
url = team_stats_url.format(year)
data = requests.get(url)

with open("team/{}.html".format(2021), "w+", encoding = "utf-8") as f:
    f.write(data.text)

In [83]:
years = list(range(1991, 2024))
dfs = []
for year in years:
    with open("team/{}.html".format(year), encoding = "utf-8") as f:
        page = f.read()
    
    print(year)
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)
    
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)

1991

AttributeError: 'NoneType' object has no attribute 'decompose'

In [64]:
teams = pd.concat(dfs)

In [65]:
teams

     W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0   56  26  .683     —  111.5  105.7   5.22  1991       Boston Celtics*
1   44  38  .537  12.0  105.4  105.6  -0.39  1991   Philadelphia 76ers*
2   39  43  .476  17.0  103.1  103.3  -0.43  1991      New York Knicks*
3   30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4   26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
..  ..  ..   ...   ...    ...    ...    ...   ...                   ...
13  42  30  .583     —  112.4  110.2   2.26  2021     Dallas Mavericks*
14  38  34  .528   4.0  113.3  112.3   1.07  2021    Memphis Grizzlies*
15  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
16  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
17  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

[1033 rows x 9 columns]

In [67]:
teams.to_csv("teams.csv")